Repository 9oormthon-univ/2024_BEOTKKOTTHON_TEAM_24_FE, pull requests merged in 2024-06, with the labels that each got.

#71 리마인드 페이지 API 연결 및 기능 구현 확인
  src/components/common/InputWithTitle.tsx
  src/components/common/InsightCard.tsx
  src/components/common/SummaryInsightCard.tsx
  src/components/folder/SummaryInsightCard.tsx
  src/components/home/header/ReminderQuestionBox.tsx
  src/components/home/header/TitleSettingPanel.tsx
  src/components/insight/Answer.tsx
  src/constants/data.ts
  src/hooks/api/useInsight.ts
  src/hooks/custom/useInsightInput.ts
  src/pages/folder/search/index.tsx
  src/pages/home/index.tsx
  src/pages/insight/[insightId]/answer/index.tsx
  src/pages/insight/[insightId]/index.tsx
  src/pages/reminder/remind-saved/index.tsx
  src/pages/upload/index.tsx
  src/pages/upload/input-text/index.tsx
  src/store/remind.tsx
  src/styles/GlobalStyle.ts
  src/types/insight.ts
  src/types/reminder.ts
Labels: ✨ Feature, 📬 API

#72 Theme provider 적용
  src/components/common/BottomBtn.tsx
  src/components/common/Header.tsx
  src/components/common/InputWithTitle.tsx
  src/components/common/InsightCard.tsx
  src/components/common/OptionalTextarea.tsx
  src/components/common/SearchSection.tsx
  src/components/common/SummaryInsightCard.tsx
  src/components/folder/ColorSelect.tsx
  src/components/folder/EditModal.tsx
  src/components/folder/RenderTagList.tsx
  src/components/folder/UploadImage.tsx
  src/components/folder/edit/RenderFolderList.tsx
  src/components/home/body/CalendarModal.tsx
  src/components/home/body/ChromeCalendar.tsx
  src/components/home/body/InsightList.tsx
  src/components/home/body/ReminderCalendar.tsx
  src/components/home/body/RenderCalendarBoard.tsx
  src/components/home/body/SafariCalendar.tsx
  src/components/home/body/full-calendar/FullCalendar.tsx
  src/components/home/body/full-calendar/RenderFullCalendarBoard.tsx
  src/components/home/header/EmptyQuestionBox.tsx
  src/components/home/header/ReminderQuestionBox.tsx
  src/components/home/header/TitleSettingPanel.tsx
  src/components/landing/Carousel.tsx
  src/components/signup/AccountSetup.tsx
  src/components/signup/AddHome.tsx
  src/components/signup/JobSetup.tsx
  src/components/signup/NameSetup.tsx
  src/components/signup/SubjectSetup.tsx
  src/components/upload/FolderSetting.tsx
  src/components/upload/Loading.tsx
  src/components/upload/RemindSetting.tsx
  src/components/upload/SelectFolderModal.tsx
  src/components/upload/SelectRemindModal.tsx
  src/components/upload/TagSection.tsx
  src/components/upload/ToggleSlider.tsx
  src/components/upload/remind-modal/DefaultPeriod.tsx
  src/components/upload/remind-modal/MonthPeriod.tsx
  src/components/upload/remind-modal/SelectRemindType.tsx
  src/components/upload/remind-modal/WeekPeriod.tsx
  src/pages/folder/[id].tsx
  src/pages/folder/delete/index.tsx
  src/pages/folder/edit-color/index.tsx
  src/pages/folder/edit/index.tsx
  src/pages/folder/index.tsx
  src/pages/folder/make/index.tsx
  src/pages/folder/search/index.tsx
  src/pages/home/index.tsx
  src/pages/insight/[insightId]/answer/index.tsx
  src/pages/insight/[insightId]/index.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/pages/upload/input-text/index.tsx
  src/pages/upload/saved/index.tsx
  src/styles/theme.ts
Labels: 🎨 Html&css

#76 [fix] #75 - css 미적용 해결
  src/components/signup/NameSetup.tsx
  src/components/signup/SubjectSetup.tsx
Labels: 🐞 BugFix, 🎨 Html&css

#78 Feature today insight
  src/components/common/InsightCard.tsx
  src/components/common/SummaryInsightCard.tsx
  src/components/home/body/ChromeCalendar.tsx
  src/components/home/body/InsightList.tsx
  src/components/home/body/ReminderCalendar.tsx
  src/components/home/body/RenderCalendarBoard.tsx
  src/constants/data.ts
  src/hooks/api/useReminder.ts
  src/store/navigation.ts
  src/store/reminder.ts
  src/store/signup.ts
  src/types/insight.ts
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#80 [fix] #79 - 인사이트 저장 시 og Image 적용되도록 변경
  src/hooks/custom/useInsightInput.ts
  src/utils/upload.ts
Labels: 🐞 BugFix, 📬 API
