Repository 9oormthon-univ/2024_BEOTKKOTTHON_TEAM_24_FE, pull requests merged in 2024-03, with the labels that each got.

#5 Feature pwa트리거
  .gitignore
  package.json
  pnpm-lock.yaml
  src/api/Insight.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/upload/index.tsx
  src/types/index.ts
Labels: enhancement

#2 [feat]: #1 - 링크 입력 시 내용 요약, 키워드 추출 기능 구현
  package.json
  pnpm-lock.yaml
  src/api/Insight.ts
  src/pages/_app.tsx
  src/pages/upload/index.tsx
Labels: enhancement

#9 [feat] #7 - CSS 초기화 및 공통 스타일 설정
  .babelrc
  package.json
  pnpm-lock.yaml
  src/components/common/MainLayout.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  src/styles/GlobalStyle.ts
  src/styles/Home.module.css
  src/styles/globals.css
Labels: ✨ Feature, 🎨 Html&css

#10 [fix] #7 - font-weight 적용 안되는 문제 해결
  src/styles/GlobalStyle.ts
Labels: 🐞 BugFix

#11 인사이트 링크 정보 가공, 자동 입력
  package.json
  pnpm-lock.yaml
  src/api/Insight.ts
  src/components/upload/MoveToNextBtn.tsx
  src/components/upload/SelectRemindModal.tsx
  src/components/upload/ToggleSlider.tsx
  src/pages/upload/index.tsx
  src/pages/upload/input-text/index.tsx
Labels: ✨ Feature

#12 폴더 선택 모달, 로딩 UI 추가
  public/loading.gif
  public/loadingBlur.png
  src/components/upload/SelectFolderModal.tsx
  src/components/upload/SelectRemindModal.tsx
  src/constants/index.ts
  src/pages/upload/index.tsx
  src/pages/upload/input-text/index.tsx
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&css

#15 [Refacor] #13 - page indicator margin 변수화
  src/components/landing/Carousel.tsx
  src/pages/landing/index.tsx
Labels: 🔨 Refactor

#18 API 타입 정의
  src/types/folder.ts
  src/types/insight.ts
  src/types/reminder.ts
  src/types/user.ts
Labels: 📬 API

#19 홈 - 리마인드 질문 컴포넌트 기능 추가
  public/svg/backspace-icon.svg
  public/svg/pencil-icon.svg
  public/svg/prev-icon.svg
  src/components/common/BottomBtn.tsx
  src/components/common/Header.tsx
  src/components/common/SummaryInsightCard.tsx
  src/components/home/InsightCard.tsx
  src/components/home/body/Calender.tsx
  src/components/home/body/InsightList.tsx
  src/components/home/body/ReminderCalender.tsx
  src/components/home/body/RenderCalenderBoard.tsx
  src/components/home/header/ReminderQuestionBox.tsx
  src/components/home/header/TitleSettingPanel.tsx
  src/components/landing/Carousel.tsx
  src/pages/home/index.tsx
  src/pages/reminder/index.tsx
  src/pages/reminder/remind-saved/index.tsx
  src/types/insight.ts
  src/types/reminder.ts
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor

#20 Feature onboard
  package.json
  pnpm-lock.yaml
  public/svg/addBtn.svg
  public/svg/unvisible-icon.svg
  public/svg/visible-icon.svg
  src/api/Insight.ts
  src/constants/PrevIcon.tsx
  src/constants/SubjectList.tsx
  src/pages/onboard/addhome/index.tsx
  src/pages/onboard/index.tsx
  src/pages/onboard/job/index.tsx
  src/pages/onboard/subject/index.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/store/signup.tsx
  src/utils/index.ts
Labels: ✨ Feature, 🎨 Html&css

#26 인사이트 제목, 요약, 키워드 추출 정상화
  src/api/Insight.ts
Labels: 🐞 BugFix

#28 PWA 아이콘 및 화면 설정
  public/favicon.ico
  public/icons/icon-114x114.png
  public/icons/icon-120x120.png
  public/icons/icon-144x144.png
  public/icons/icon-152x152.png
  public/icons/icon-180x180.png
  public/icons/icon-192x192.png
  public/icons/icon-256x256.png
  public/icons/icon-36x36.png
  public/icons/icon-384x384.png
  public/icons/icon-48x48.png
  public/icons/icon-512x512.png
  public/icons/icon-57x57.png
  public/icons/icon-60x60.png
  public/icons/icon-72x72.png
  public/icons/icon-76x76.png
  public/icons/icon-96x96.png
  public/image/favicon.png
  public/manifest.json
  public/svg/addBtn.svg
  public/svg/calender-stamp.svg
  public/svg/favicon.svg
  public/svg/reinput-folder.svg
  src/components/common/BottomNavigation.tsx
  src/components/home/body/InsightList.tsx
  src/components/home/body/ReminderCalender.tsx
  src/components/home/body/RenderCalenderBoard.tsx
  src/components/upload/SelectFolderModal.tsx
  src/components/upload/SelectRemindModal.tsx
  src/components/upload/ToggleSlider.tsx
  src/constants/landing.tsx
  src/pages/_document.tsx
  src/pages/upload/input-text/index.tsx
Labels: 🐞 BugFix

#30 폴더 탭 UI
  public/svg/folder/blue-folder-big-icon.svg
  public/svg/folder/blue-folder-large-icon.svg
  public/svg/folder/blue-folder-small-icon.svg
  public/svg/folder/circle-with-check-icon.svg
  public/svg/folder/edit-pencil-icon.svg
  public/svg/folder/green-folder-big-icon.svg
  public/svg/folder/green-folder-large-icon.svg
  public/svg/folder/green-folder-small-icon.svg
  public/svg/folder/orange-folder-big-icon.svg
  public/svg/folder/orange-folder-large-icon.svg
  public/svg/folder/orange-folder-small-icon.svg
  public/svg/folder/pink-folder-big-icon.svg
  public/svg/folder/pink-folder-large-icon.svg
  public/svg/folder/pink-folder-small-icon.svg
  public/svg/folder/purple-folder-big-icon.svg
  public/svg/folder/purple-folder-large-icon.svg
  public/svg/folder/purple-folder-small-icon.svg
  public/svg/folder/trash-icon.svg
  public/svg/folder/yellow-folder-big-icon.svg
  public/svg/folder/yellow-folder-large-icon.svg
  public/svg/folder/yellow-folder-small-icon.svg
  public/svg/onboard/design-image.svg
  public/svg/onboard/developer-image.svg
  public/svg/onboard/phone-image.svg
  public/svg/onboard/planner-image.svg
  public/svg/search-icon.svg
  src/api/folder/folderDelete.ts
  src/api/index.ts
  src/components/common/BottomBtn.tsx
  src/components/folder/ColorSelect.tsx
  src/components/folder/EditModal.tsx
  src/constants/FolderList.tsx
  src/constants/colors.tsx
  src/pages/folder/delete/index.tsx
  src/pages/folder/edit-color/index.tsx
  src/pages/folder/edit/index.tsx
  src/pages/folder/index.tsx
  src/pages/folder/make/index.tsx
  src/pages/onboard/addhome/index.tsx
  src/pages/onboard/job/index.tsx
  src/pages/signin/index.tsx
  src/utils/folder.tsx
Labels: ✨ Feature, 🎨 Html&css

#31 API 초기 세팅
  next.config.mjs
  src/api/Insight.ts
  src/api/auth.ts
  src/api/folder.ts
  src/api/folder/folderDelete.ts
  src/api/hello.ts
  src/api/index.ts
  src/api/insight.ts
  src/api/interceptors.ts
  src/api/reminder.ts
  src/constants/window.ts
  src/hooks/api/useAuth.ts
  src/hooks/api/useFolder.ts
  src/hooks/api/useInsight.ts
  src/hooks/api/useReminder.ts
  src/pages/upload/input-text/index.tsx
  src/types/folder.ts
  src/types/insight.ts
  src/types/user.ts
  src/utils/auth.ts
Labels: 📬 API

#32 Feature folder
  public/svg/copy-icon.svg
  public/svg/glass-icon.svg
  public/svg/share-icon-blue.svg
  src/components/folder/EditModal.tsx
  src/pages/folder/[id].tsx
  src/pages/folder/edit/index.tsx
  src/pages/folder/index.tsx
Labels: ✨ Feature, 🎨 Html&css

#34 [feat] #33 - 회원가입, 온보딩, 로그인 API 연결
  src/api/auth.ts
  src/api/folder.ts
  src/api/index.ts
  src/api/insight.ts
  src/hooks/api/useFolder.ts
  src/pages/onboard/addhome/index.tsx
  src/pages/onboard/subject/index.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/pages/upload/index.tsx
  src/store/signup.tsx
  src/types/user.ts
  src/utils/auth.ts
Labels: 📬 API

#35 홈 - 캘린더 추가 기능 & CSS 수정
  public/svg/down-icon.svg
  public/svg/insight-favicon.svg
  src/components/common/BottomNavigation.tsx
  src/components/common/SummaryInsightCard.tsx
  src/components/folder/EditModal.tsx
  src/components/home/InsightCard.tsx
  src/components/home/body/Calender.tsx
  src/components/home/body/CalenderModal.tsx
  src/components/home/body/InsightList.tsx
  src/components/home/body/ReminderCalender.tsx
  src/components/home/body/RenderCalenderBoard.tsx
  src/components/home/body/full-calender/FullCalender.tsx
  src/components/home/body/full-calender/RenderFullCalenderBoard.tsx
  src/components/upload/SelectFolderModal.tsx
  src/components/upload/SelectRemindModal.tsx
  src/pages/_document.tsx
  src/pages/folder/[id].tsx
  src/pages/folder/delete/index.tsx
  src/pages/home/index.tsx
  src/pages/reminder/index.tsx
  src/pages/upload/index.tsx
  src/pages/upload/input-text/index.tsx
  src/styles/GlobalStyle.ts
  src/types/reminder.ts
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&css

#36 Feature 인사이트가공
  public/image/defaultImage.jpeg
  src/api/folder.ts
  src/api/insight.ts
  src/components/upload/SelectFolderModal.tsx
  src/components/upload/SelectRemindModal.tsx
  src/hooks/api/useInsight.ts
  src/pages/signin/index.tsx
  src/pages/upload/index.tsx
  src/pages/upload/input-text/index.tsx
  src/types/insight.ts
Labels: 🐞 BugFix, 📬 API

#38 Feature 인사이트가공
  src/api/insight.ts
  src/components/upload/SelectFolderModal.tsx
  src/hooks/LocalStorage.ts
  src/hooks/api/useInsight.ts
  src/pages/signin/index.tsx
  src/pages/upload/index.tsx
  src/pages/upload/input-text/index.tsx
Labels: 📬 API

#39 Feature 인사이트가공
  src/pages/upload/index.tsx
  src/pages/upload/input-text/index.tsx
  src/pages/upload/saved/index.tsx
Labels: ✨ Feature, 📬 API

#40 Feature 인사이트가공
  src/components/upload/SelectRemindModal.tsx
  src/pages/folder/[id].tsx
  src/pages/upload/index.tsx
  src/pages/upload/input-text/index.tsx
Labels: 🐞 BugFix
