Repository 9oormthon-univ/2024_BEOTKKOTTHON_TEAM_24_FE, pull requests merged in 2024-05, with the labels that each got.

#59 인사이트 저장 (정보, 이미지, mainImage) API 적용
  next.config.mjs
  src/api/insight.ts
  src/components/folder/UploadImage.tsx
  src/hooks/api/useInsight.ts
  src/pages/upload/index.tsx
  src/pages/upload/input-text/index.tsx
  src/pages/upload/saved/index.tsx
  src/types/insight.ts
  src/utils/upload.ts
Labels: ✨ Feature, 📬 API

#58 Home 화면 애니메이션 분기 처리
  public/svg/calendar-stamp.svg
  src/api/reminder.ts
  src/components/home/body/CalendarModal.tsx
  src/components/home/body/Calender.tsx
  src/components/home/body/ChromeCalendar.tsx
  src/components/home/body/InsightList.tsx
  src/components/home/body/ReminderCalendar.tsx
  src/components/home/body/RenderCalendarBoard.tsx
  src/components/home/body/SafariCalendar.tsx
  src/components/home/body/full-calendar/FullCalendar.tsx
  src/components/home/body/full-calendar/RenderFullCalendarBoard.tsx
  src/constants/data.ts
  src/hooks/api/useReminder.ts
  src/pages/folder/[id].tsx
  src/pages/home/index.tsx
  src/types/reminder.ts
Labels: 🐞 BugFix

#57 Refactor/insight
  src/api/insight.ts
  src/hooks/api/useInsight.ts
  src/hooks/custom/useInsightInput.ts
  src/hooks/custom/useLinkInput.ts
  src/pages/upload/index.tsx
  src/pages/upload/input-text/index.tsx
  src/types/insight.ts
  src/utils/upload.ts
Labels: 🔨 Refactor

#62 헤더 컴포넌트 재사용성 강화
  src/components/common/Header.tsx
Labels: 🎨 Html&css, 🔨 Refactor

#64 InsightCard 태그 리스트 오류 수정
  src/components/common/InsightCard.tsx
Labels: 🐞 BugFix

#65 ThemeProvider 디자인 시스템 색상, 타이포 추가
  src/pages/_app.tsx
  src/styles/styled-components.d.ts
  src/styles/theme.ts
Labels: ✨ Feature, 🎨 Html&css

#67 폴더 페이지 api 연결 및 기능 구현 확인
  public/svg/modal-handle-bar.svg
  src/components/common/BottomBtn.tsx
  src/components/common/Header.tsx
  src/components/folder/ColorSelect.tsx
  src/components/folder/EditModal.tsx
  src/components/folder/RenderTagList.tsx
  src/components/folder/edit/RenderFolderList.tsx
  src/hooks/api/useFolder.ts
  src/hooks/custom/useCopyClipboard.ts
  src/pages/folder/[id].tsx
  src/pages/folder/delete/index.tsx
  src/pages/folder/edit-color/index.tsx
  src/pages/folder/edit/index.tsx
  src/pages/folder/index.tsx
  src/pages/folder/make/index.tsx
  src/pages/upload/index.tsx
  src/pages/upload/input-text/index.tsx
  src/types/folder.ts
Labels: ✨ Feature, 🎨 Html&css, 📬 API, 🔨 Refactor

#68 회원가입 절차 useFunnel 적용
  src/components/signup/AccountSetup.tsx
  src/components/signup/AddHome.tsx
  src/components/signup/JobSetup.tsx
  src/components/signup/NameSetup.tsx
  src/components/signup/SubjectSetup.tsx
  src/hooks/api/useAuth.ts
  src/hooks/custom/useFunnel.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/signup/index.tsx
  src/types/Funnel.ts
Labels: ✨ Feature, 🔨 Refactor
